allow_list:
  - acpica-devel
  - alsa-devel
  - amd-gfx
  - arm-scmi
  - asahi
  - ath11k
  - ath12k
  - ath9k-devel
  - audit
  - autofs
  - b43-dev
  - backports
  - barebox
  - batman
  - bitbake-devel
  - bpf
  - brcm80211
  - bridge
  - buildroot
  - c-std-porting
  - ccan
  - ceph-devel
  - cgroups
  - chrome-platform
  - cip-dev
  - cocci
  - coconut-svsm
  - connman
  - containers
  - cpufreq
  - criu
  - cryptsetup
  - cti-tac
  - damon
  - dash
  - dccp
  - ddprobe
  - devicetree-compiler
  - devicetree-spec
  - diamon-discuss
  - distributions
  - dm-crypt
  - dm-devel
  - dpdk-dev
  - drbd-announce
  - drbd-dev
  - dri-devel
  - driver-core
  - dtrace
  - dwarves
  - ecryptfs
  - ell
  - fio
  - fstests
  - fsverity
  - fuego
  - fuse-devel
  - gfs2
  - grub-devel
  - hail-devel
  - historical-speck
  - igt-dev
  - imx
  - initramfs
  - intel-gfx
  - intel-wired-lan
  - intel-xe
  - io-uring
  - iwd
  - kbd
  - kdevops
  - kernel-hardening
  - kernel-janitors
  - kernel-testers
  - kernel-tls-handshake
  - kernelci
  - kernelnewbies
  - kexec
  - keyrings
  - keys
  - ksummit
  - kvm
  - kvm-ia64
  - kvm-ppc
  - kvmarm
  - landlock
  - lartc
  - lch
  - liba2i
  - linux-8086
  - linux-acpi
  - linux-admin
  - linux-alpha
  - linux-amlogic
  - linux-api
  - linux-arch
  - linux-arm-kernel
  - linux-arm-msm
  - linux-aspeed
  - linux-assembly
  - linux-audit
  - linux-bcache
  - linux-bcachefs
  - linux-block
  - linux-bluetooth
  - linux-btrace
  - linux-btrfs
  - linux-bugs
  - linux-c-programming
  - linux-can
  - linux-cifs
  - linux-clk
  - linux-config
  - linux-console
  - linux-crypto
  - linux-csky
  - linux-cve-announce
  - linux-cxl
  - linux-debuggers
  - linux-devicetree
  - linux-diald
  - linux-doc
  - linux-edac
  - linux-efi
  - linux-embedded
  - linux-erofs
  - linux-ext4
  - linux-f2fs-devel
  - linux-fbdev
  - linux-firmware
  - linux-fpga
  - linux-fscrypt
  - linux-fsdevel
  - linux-gcc
  - linux-gpio
  - linux-hams
  - linux-hexagon
  - linux-hotplug
  - linux-hwmon
  - linux-hyperv
  - linux-i2c
  - linux-i3c
  - linux-ia64
  - linux-ide
  - linux-iio
  - linux-input
  - linux-iommu
  - linux-kbuild
  - linux-kernel-announce
  - linux-kernel-mentees
  - linux-kselftest
  - linux-laptop
  - linux-leds
  - linux-lvm
  - linux-m68k
  - linux-man
  - linux-media
  - linux-mediatek
  - linux-metag
  - linux-mips
  - linux-mm
  - linux-mmc
  - linux-modules
  - linux-msdos
  - linux-mtd
  - linux-newbie
  - linux-next
  - linux-nfc
  - linux-nfs
  - linux-nilfs
  - linux-numa
  - linux-nvme
  - linux-omap
  - linux-oxnas
  - linux-patches
  - linux-pci
  - linux-perf-users
  - linux-phy
  - linux-pm
  - linux-ppp
  - linux-pwm
  - linux-raid
  - linux-rdma
  - linux-remoteproc
  - linux-renesas-soc
  - linux-riscv
  - linux-rockchip
  - linux-rt-devel
  - linux-rt-users
  - linux-rtc
  - linux-s390
  - linux-safety
  - linux-samsung-soc
  - linux-scsi
  - linux-sctp
  - linux-security-module
  - linux-serial
  - linux-sgx
  - linux-sh
  - linux-smp
  - linux-snps-arc
  - linux-sound
  - linux-sparse
  - linux-spdx
  - linux-spi
  - linux-staging
  - linux-sunxi
  - linux-tegra
  - linux-toolchains
  - linux-trace-devel
  - linux-trace-kernel
  - linux-trace-users
  - linux-unionfs
  - linux-usb
  - linux-watchdog
  - linux-wireless
  - linux-wpan
  - linux-x11
  - linux-x25
  - linux-xfs
  - linuxppc-dev
  - live-patching
  - lkml
  - lkmm
  - llvm
  - loongarch
  - ltp
  - lttng-dev
  - lustre-devel
  - lvfs-announce
  - lvfs-general
  - lvm-devel
  - lvs-devel
  - mailbox
  - mhi
  - mlmmj
  - mm-commits
  - multikernel
  - netdev
  - netfilter
  - netfilter-devel
  - netfs
  - nil-migration
  - nouveau
  - nova-gpu
  - ntb
  - ntfs3
  - nvdimm
  - ocfs2-devel
  - oe-chipsec
  - oe-kbuild
  - oe-kbuild-all
  - oe-linux-nfc
  - oe-lkp
  - ofono
  - op-tee
  - opae
  - openbmc
  - openembedded-core
  - openembedded-devel
  - openrisc
  - opensbi
  - openvpn-devel
  - outreachy
  - perfbook
  - phone-devel
  - platform-driver-x86
  - poky
  - powertop
  - printing-architecture
  - printing-users
  - qemu-arm
  - qemu-devel
  - qemu-riscv
  - qemu-rust
  - qemu-trivial
  - quic
  - radiotap
  - rcu
  - regressions
  - reiserfs-devel
  - rpdfs-devel
  - rust-for-linux
  - sashiko-reviews
  - sched-ext
  - selinux
  - selinux-refpolicy
  - signatures
  - smatch
  - soc
  - sophgo
  - spacemit
  - sparclinux
  - spdk
  - stable
  - stable-rt
  - stgt
  - syzbot
  - target-devel
  - tech-board-discuss
  - timestamp
  - tools
  - tpm-protocol
  - tpm2
  - tpmdd-devel
  - trinity
  - u-boot
  - u-boot-amlogic
  - ultralinux
  - util-linux
  - v9fs
  - virtio-comment
  - virtio-dev
  - virtio-fs
  - virtualization
  - wireguard
  - wireless-regdb
  - workflows
  - x86-cpuid
  - xdp-newbies
  - xdp2
  - xen-devel
  - xenomai
  - xfs-stable
